FROM node:22

# Set working directory
WORKDIR /app

# Copy only package files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Then copy the rest
COPY . .


CMD ["npm","run","dev"]




